[package]
name = "chagents"
version = "0.1.0"
authors = ["ikkamens <ikkamens@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.1.1"
lazy_static = "1.4.0"
rand = "0.7.3"
